pub enum BuildingType {
    // ArcheryRange,
    // Barracks,
    // Blacksmith,
    // BombardTower,
    // Castle,
    // CastleGate,
    // CastleWall,
    // Cathedral,
    // Church,
    // Dock,
    // Farm,
    // FortifiedGate,
    // FortifiedWall,
    // Gate,
    // GoldCamp,
    // GuardTower,
    // House,
    // Keep,
    // LumberCamp,
    // Market,
    // Mill,
    // Mine,
    // Monastery,
    // Outpost,
    // PalisadeGate,
    // PalisadeWall,
    // SiegeWorkshop,
    // Stable,
    // StoneCamp,
    // StoneGate,
    // StoneWall,
    // Tower,
    // TownCenter,
    // University,
    // Wall,
    // WatchTower,
}

#[derive(Clone, Debug)]
pub enum ActionType {
    // Move,
    // Attack,
    EnableBuildMode,
}
